import { title } from 'process';
import { Shop, Offer, Job, Ad } from '../types';

export const AREAS = ['Theni Main', 'Allinagaram', 'Periyakulam', 'Bodinayakanur', 'Cumbum', 'Chinnamanur', 'Andipatti', 'Thenkarai'];

export const CATEGORY_HIERARCHY: Record<string, string[]> = {
  'Food & Dining': ['Restaurants', 'Vegetarian Restaurants', 'Non-Veg Restaurants', 'Multi-Cuisine Restaurants', 'Cafes', 'Bakeries', 'Sweet Shops', 'Ice Cream & Juice Shops', 'Tea & Coffee Shops', 'Fast Food / Snacks', 'Catering Services', 'Home Food / Tiffin Services', 'Cake Order Services', 'Cloud Kitchens'],
  'Fashion & Apparel': ['Men’s Wear', 'Women’s Wear', 'Kids Wear', 'Saree Shops', 'Textile Stores', 'Boutiques & Designer Wear', 'Innerwear & Lingerie', 'Footwear Stores', 'Bags & Wallets', 'Fashion Accessories', 'School Uniform Shops'],
  'Electronics & Appliances': ['Mobile Showrooms', 'Laptop Stores', 'TV / AC / Fridge Dealers', 'Home Appliances Stores', 'CCTV & Security Systems', 'Mobile Accessories', 'Computer Accessories', 'Inverter & Battery Shops'],
  'Grocery & Daily Needs': ['Supermarkets', 'Grocery Stores', 'Organic Stores', 'Fruits & Vegetables', 'Dairy & Milk Products', 'Meat & Fish Shops', 'Pet Food & Pet Stores', 'General Stores'],
  'Home & Living': ['Furniture Stores', 'Mattress Stores', 'Kitchenware Shops', 'Home Decor & Gift Items', 'Modular Kitchen Showrooms', 'Interior Showrooms', 'Curtains & Blind Shops', 'Lighting & Electrical Shops', 'Home Essentials (Towels, Bedsheets)'],
  'Jewellery & Accessories': ['Gold Jewellery', 'Silver Jewellery', 'Platinum Jewellery', 'Diamond Jewellery', 'Imitation Jewellery', 'Gift & Fancy Stores', 'Watches & Timepiece Stores'],
  'Beauty & Personal Care': ['Beauty Parlours', 'Men’s Salons', 'Spa & Massage', 'Bridal Makeup Studios', 'Cosmetics Stores', 'Perfume Stores', 'Nail Studios', 'Skincare Treatment Centers'],
  'Automobile (Sales & Services)': ['Bike Showrooms', 'Car Showrooms', 'Used Car/Used Bike Dealers', 'Car Wash', 'Bike Service Centers', 'Car Service Centers', 'Auto Detailing / Ceramic Coating', 'Tyre Shops', 'Battery Shops', 'Car/Bike Accessories'],
  'Healthcare & Wellness': ['Hospitals', 'Clinics', 'Dental Clinics', 'Eye Clinics', 'Physiotherapy Centres', 'Diagnostic Centres / Labs', 'Medical Shops', 'Surgical Equipment Shops', 'Optical Stores', 'Hearing Aid Stores', 'Fitness Trainers', 'Yoga Centres'],
  'Home Services': ['Electricians', 'Plumbers', 'AC Mechanic / AC Service', 'RO Water Purifier Service', 'Painting Contractors', 'Pest Control', 'Cleaning Services', 'Carpenter', 'Tiles & Granite Work', 'Borewell Service'],
  'Creative, Media & Printing': ['Photography Studios', 'Videography Teams', 'Album Designing', 'Printing Press', 'Flex & Branding Shops', 'Digital Marketing Agencies', 'Social Media Managers', 'Script & Content Writers'],
  'Education & Training': ['Tuition Centres', 'Coaching Institutes', 'Computer Training', 'Languages & Spoken English', 'Skill Development Centers', 'Dance Classes', 'Music Classes', 'Arts & Craft Classes', 'Competitive Exam Coaching'],
  'Events & Celebrations': ['Event Planners', 'Decoration Services', 'Wedding Planners', 'Catering Services', 'Stage Sound & Lighting', 'Mandapam / Banquet Halls', 'Photography/Videography', 'DJ Services', 'Costume Rentals'],
  'Professional Services': ['Advocates', 'Chartered Accountants', 'Tax Consultants', 'Architects', 'Interior Designers', 'Civil Engineers', 'Real Estate Agents', 'Insurance Agents', 'Travel Agents'],
  'Agriculture & Industrial': ['Agri Fertilizer Shops', 'Pesticide Shops', 'Seeds & Plants Nursery', 'Tractor & Agri Tools', 'Industrial Equipment Dealers', 'Welding & Fabrication Shops'],
  'Stationery, Books & Kids': ['Book Stores', 'Stationery Shops', 'Toy Shops', 'Baby Products Stores', 'School Supplies', 'Gift Shops'],
  'Sports & Lifestyle': ['Sports Shops', 'Gym Equipment Stores', 'Outdoor Gear', 'Cycle Stores'],
  'Real Estate & Construction': ['Property Agents', 'Land Promoters', 'Construction Companies', 'Hardware Shops', 'Cement & Steel Dealers', 'Tiles & Sanitary Ware Shops'],
  'Pets & Animals': ['Pet Shops', 'Pet Food Stores', 'Veterinary Clinics', 'Animal Care Services'],
  'Online & Digital Services': ['Website Development', 'App Development', 'SEO Services', 'Google Ads Management', 'Graphic Designing', 'Video Editing Services']
};

export const CATEGORY_IMAGES: Record<string, string> = {
  'Food & Dining': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=400',
  'Fashion & Apparel': 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=400',
  'Electronics & Appliances': 'https://images.unsplash.com/photo-1609592424367-17e997a6f23f?auto=format&fit=crop&q=80&w=400',
  'Grocery & Daily Needs': 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=400',
  'Home & Living': 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=400',
  'Jewellery & Accessories': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=400',
  'Beauty & Personal Care': 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&q=80&w=400',
  'Automobile (Sales & Services)': 'https://images.unsplash.com/photo-1486262715619-01b80250e0dc?auto=format&fit=crop&q=80&w=400',
  'Healthcare & Wellness': 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=400',
  'Home Services': 'https://images.unsplash.com/photo-1505798577917-a651a5d40318?auto=format&fit=crop&q=80&w=400',
  'Creative, Media & Printing': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=400',
  'Education & Training': 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=400',
  'Events & Celebrations': 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=400',
  'Professional Services': 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=400',
  'Agriculture & Industrial': 'https://images.unsplash.com/photo-1625246333195-58197bd47f26?auto=format&fit=crop&q=80&w=400',
  'Stationery, Books & Kids': 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=400',
  'Sports & Lifestyle': 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=400',
  'Real Estate & Construction': 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=400',
  'Pets & Animals': 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&q=80&w=400',
  'Online & Digital Services': 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=400'
};

export const CATEGORIES = Object.keys(CATEGORY_HIERARCHY);

export const mockShops: Shop[] = [
  {
    id: 's1',
    name: 'Theni Mobiles & Gadgets',
    category: 'Electronics & Appliances',
    subCategory: 'Mobiles',
    description: 'The best place for smartphones, accessories, and repairs in Theni.',
    address: '123 Bazaar Street, Theni',
    area: 'Theni Main',
    contactNumber: '9876543210',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Theni+Mobiles&background=0f766e&color=fff&size=256',
    rating: 4.8,
    socialMedia: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com',
      whatsapp: '919876543210',
      linkedin: 'https://linkedin.com',
      website: 'https://example.com'
    }
  },
  {
    id: 's2',
    name: 'Saravana Textiles',
    category: 'Fashion & Apparel',
    subCategory: 'Women',
    description: 'Silk sarees, readymade garments, and wedding collections for the whole family.',
    address: '45 Temple Road, Allinagaram',
    area: 'Allinagaram',
    contactNumber: '9876543211',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Saravana+Textiles&background=e11d48&color=fff&size=256',
    rating: 4.5,
    socialMedia: {
      instagram: 'https://instagram.com',
      whatsapp: '919876543211'
    }
  },
  {
    id: 's3',
    name: 'Spice Valley Restaurant',
    category: 'Food & Dining',
    subCategory: 'Restaurant',
    description: 'Authentic Chettinad, Chinese, and Tandoori cuisine with family AC dining.',
    address: '88 High Road, Periyakulam',
    area: 'Periyakulam',
    contactNumber: '9876543212',
    isPremium: false,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Spice+Valley&background=f59e0b&color=fff&size=256',
    rating: 4.2,
    socialMedia: {
      facebook: 'https://facebook.com',
      whatsapp: '919876543212',
      website: 'https://example.com'
    }
  },
  {
    id: 's4',
    name: 'Green Leaf Groceries',
    category: 'Grocery & Daily Needs',
    subCategory: 'Organic',
    description: 'Fresh organic vegetables and daily essentials delivered to your doorstep.',
    address: '12 Market Lane, Bodinayakanur',
    area: 'Bodinayakanur',
    contactNumber: '9876543213',
    isPremium: false,
    isVerified: false,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Green+Leaf&background=10b981&color=fff&size=256',
    rating: 4.0
  },
  {
    id: 's5',
    name: 'Auto Care Experts',
    category: 'Automobile (Sales & Services)',
    subCategory: 'Car Service',
    description: 'Complete car and bike servicing, water wash, and detailing.',
    address: 'NH 85, Theni',
    area: 'Theni Main',
    contactNumber: '9876543214',
    isPremium: false,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1486262715619-01b80250e0dc?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Auto+Care&background=6366f1&color=fff&size=256',
    rating: 4.6,
    socialMedia: {
      whatsapp: '919876543214',
      facebook: 'https://facebook.com'
    }
  },
  {
    id: 's6',
    name: 'City Trends',
    category: 'Fashion & Apparel',
    subCategory: 'Men',
    description: 'Trendy western wear and accessories for youth.',
    address: 'City Mall, Cumbum',
    area: 'Cumbum',
    contactNumber: '9876543215',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=City+Trends&background=8b5cf6&color=fff&size=256',
    rating: 4.3,
    socialMedia: {
      instagram: 'https://instagram.com',
      website: 'https://example.com'
    }
  },
  {
    id: 's7',
    name: 'Theni Gold House',
    category: 'Jewellery & Accessories',
    subCategory: 'Gold',
    description: '916 Hallmarked gold jewellery and diamond collections.',
    address: 'Near Bus Stand, Theni',
    area: 'Theni Main',
    contactNumber: '9876543216',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Theni+Gold&background=d97706&color=fff&size=256',
    rating: 4.9,
    socialMedia: {
      facebook: 'https://facebook.com',
      whatsapp: '919876543216'
    }
  },
  {
    id: 's8',
    name: 'Vetri Computers',
    category: 'Electronics & Appliances',
    subCategory: 'Laptops',
    description: 'Laptops, desktops, printers, and CCTV installation services.',
    address: 'East Street, Chinnamanur',
    area: 'Chinnamanur',
    contactNumber: '9876543217',
    isPremium: false,
    isVerified: false,
    image: 'https://images.unsplash.com/photo-1597872252165-4828b60d9538?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Vetri+Computers&background=3b82f6&color=fff&size=256',
    rating: 4.1,
    socialMedia: {
      linkedin: 'https://linkedin.com'
    }
  },
  {
    id: 's9',
    name: 'Annapoorna Mess',
    category: 'Food & Dining',
    subCategory: 'Restaurant',
    description: 'Homely vegetarian meals and catering services.',
    address: 'West Car Street, Andipatti',
    area: 'Andipatti',
    contactNumber: '9876543218',
    isPremium: false,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Annapoorna&background=ef4444&color=fff&size=256',
    rating: 4.7
  },
  {
    id: 's10',
    name: 'Royal Fitness Gym',
    category: 'Healthcare & Wellness',
    subCategory: 'Gym',
    description: 'Modern equipment, personal training, and cardio sections.',
    address: 'Bypass Road, Theni',
    area: 'Theni Main',
    contactNumber: '9876543219',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Royal+Fitness&background=14b8a6&color=fff&size=256',
    rating: 4.5,
    socialMedia: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      whatsapp: '919876543219',
      website: 'https://example.com'
    }
  },
  {
    id: 's11',
    name: 'A2B Sweets & Bakery',
    category: 'Food & Dining',
    subCategory: 'Bakery',
    description: 'Premium sweets, snacks and bakery items for all occasions.',
    address: 'Madurai Road, Theni',
    area: 'Theni Main',
    contactNumber: '9876543220',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=A2B+Sweets&background=f97316&color=fff&size=256',
    rating: 4.6
  },
  {
    id: 's12',
    name: 'Poorvika Mobiles',
    category: 'Electronics & Appliances',
    subCategory: 'Mobiles',
    description: 'One stop shop for all mobile phones and accessories.',
    address: 'Near Old Bus Stand, Theni',
    area: 'Theni Main',
    contactNumber: '9876543221',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1556656793-02715d8dd660?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Poorvika&background=ec4899&color=fff&size=256',
    rating: 4.7,
    socialMedia: {
      website: 'https://poorvika.com'
    }
  },
  {
    id: 's13',
    name: 'Apollo Pharmacy',
    category: 'Healthcare & Wellness',
    subCategory: 'Pharmacy',
    description: '24/7 Pharmacy and medical store.',
    address: 'Hospital Road, Periyakulam',
    area: 'Periyakulam',
    contactNumber: '9876543222',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Apollo&background=0284c7&color=fff&size=256',
    rating: 4.4,
    socialMedia: {
      website: 'https://apollopharmacy.in'
    }
  },
  {
    id: 's14',
    name: 'Trends Men',
    category: 'Fashion & Apparel',
    subCategory: 'Men',
    description: 'Exclusive mens wear collection.',
    address: 'Bypass Road, Theni',
    area: 'Theni Main',
    contactNumber: '9876543223',
    isPremium: true,
    isVerified: true,
    image: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&q=80&w=800',
    logo: 'https://ui-avatars.com/api/?name=Trends+Men&background=111827&color=fff&size=256',
    rating: 4.5
  }
];

export const mockOffers: Offer[] = [
  {
    id: 'o1',
    title: '50% Off on Smartphones',
    description: 'Get flat 50% off on selected models. Limited time offer.',
    discountPercentage: 50,
    validUntil: '2024-12-31',
    category: 'Electronics & Appliances',
    subCategory: 'Mobiles',
    shopId: 's1',
    location: 'Theni Main',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1598327773204-7c3311b93a29?auto=format&fit=crop&q=80&w=800',
    originalPrice: 20000,
    offerPrice: 10000,
    terms: "Valid on Samsung and Xiaomi models only. One offer per customer.",
    code: "THENI50"
  },
  {
    id: 'o2',
    title: 'Buy 1 Get 1 Free Sarees',
    description: 'Aadi sale bonanza! Buy any silk saree and get one free.',
    discountPercentage: 50,
    validUntil: '2024-08-15',
    category: 'Fashion & Apparel',
    subCategory: 'Women’s Wear',
    shopId: 's2',
    location: 'Allinagaram',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    terms: "Offer applicable on sarees above ₹1000. No exchange.",
    code: "BOGO24"
  },
  {
    id: 'o3',
    title: 'Family Combo Meal Deal',
    description: 'Chicken Biryani family pack with starters and drinks at ₹999.',
    discountPercentage: 20,
    validUntil: '2024-12-31',
    category: 'Food & Dining',
    subCategory: 'Restaurant',
    shopId: 's3',
    location: 'Periyakulam',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&q=80&w=800',
    originalPrice: 1250,
    offerPrice: 999,
    terms: "Valid for dine-in and takeaway. Not valid on weekends.",
    code: "FAMFEAST"
  },
  {
    id: 'o4',
    title: 'Car Wash Offer',
    description: 'Full foam wash and interior cleaning.',
    discountPercentage: 30,
    validUntil: '2024-11-30',
    category: 'Automobile (Sales & Services)',
    subCategory: 'Car Wash',
    shopId: 's5',
    location: 'Theni Main',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&q=80&w=800',
    originalPrice: 800,
    offerPrice: 560,
    terms: "Prior appointment recommended. Valid for hatchbacks and sedans.",
    code: "WASH30"
  },
  {
    id: 'o5',
    title: 'Mens Jeans Clearance',
    description: 'Flat ₹500 off on branded jeans.',
    discountPercentage: 40,
    validUntil: '2024-10-01',
    category: 'Fashion & Apparel',
    subCategory: 'Men',
    shopId: 's6',
    location: 'Cumbum',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1542272617-08f08630329e?auto=format&fit=crop&q=80&w=800',
    terms: "Valid on selected brands only. While stocks last.",
    code: "JEAN500"
  },
  {
    id: 'o6',
    title: 'No Making Charges',
    description: '0% Making charges on Gold Coins.',
    discountPercentage: 10,
    validUntil: '2024-11-15',
    category: 'Jewellery & Accessories',
    subCategory: 'Gold',
    shopId: 's7',
    location: 'Theni Main',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&q=80&w=800',
    terms: "Valid on purchase of 8g coins and above.",
    code: "GOLD0VA"
  },
  {
    id: 'o7',
    title: 'Free Antivirus Installation',
    description: 'Free antivirus with every laptop service.',
    discountPercentage: 100,
    validUntil: '2024-09-30',
    category: 'Electronics & Appliances',
    subCategory: 'Laptops',
    shopId: 's8',
    location: 'Chinnamanur',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800',
    originalPrice: 500,
    offerPrice: 0,
    terms: "Valid for general service only.",
    code: "FREEAV"
  },
  {
    id: 'o8',
    title: 'Unlimited Meals ₹120',
    description: 'Unlimited veg meals for lunch.',
    discountPercentage: 15,
    validUntil: '2024-12-31',
    category: 'Food & Dining',
    subCategory: 'Restaurant',
    shopId: 's9',
    location: 'Andipatti',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=800',
    originalPrice: 150,
    offerPrice: 120,
    terms: "Valid only for lunch (12PM - 3PM).",
    code: "MEAL120"
  },
  {
    id: 'o9',
    title: 'Annual Gym Membership',
    description: 'Pay for 10 months and get 2 months free.',
    discountPercentage: 20,
    validUntil: '2025-01-01',
    category: 'Healthcare & Wellness',
    subCategory: 'Gym',
    shopId: 's10',
    location: 'Theni Main',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&q=80&w=800',
    originalPrice: 12000,
    offerPrice: 10000,
    terms: "Non-refundable. Non-transferable.",
    code: "FITYEAR"
  },
  {
    id: 'o10',
    title: 'Organic Honey Sale',
    description: 'Pure forest honey 1kg buy now.',
    discountPercentage: 10,
    validUntil: '2024-10-20',
    category: 'Grocery & Daily Needs',
    subCategory: 'Organic',
    shopId: 's4',
    location: 'Bodinayakanur',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800',
    originalPrice: 800,
    offerPrice: 720,
    terms: "Limited stock available.",
    code: "HONEY10"
  },
  {
    id: 'o11',
    title: 'Wedding Silk Saree',
    description: 'Exclusive Kancheepuram Silk Sarees at wholesale price.',
    discountPercentage: 25,
    validUntil: '2024-12-01',
    category: 'Fashion & Apparel',
    subCategory: 'Women',
    shopId: 's2',
    location: 'Allinagaram',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1583391733958-e0267c7b3986?auto=format&fit=crop&q=80&w=800',
    originalPrice: 25000,
    offerPrice: 18750,
    terms: "Valid on wedding collection only.",
    code: "SILK25"
  },
  {
    id: 'o12',
    title: 'Bluetooth Speakers',
    description: 'Portable speakers starting from ₹499.',
    discountPercentage: 40,
    validUntil: '2024-11-10',
    category: 'Electronics & Appliances',
    subCategory: 'Accessories',
    shopId: 's1',
    location: 'Theni Main',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800',
    originalPrice: 900,
    offerPrice: 499,
    terms: "Warranty applicable as per manufacturer.",
    code: "SOUND40"
  },
  {
    id: 'o13',
    title: 'Sweets Box Offer',
    description: 'Flat 10% off on 1kg mixed sweets box.',
    discountPercentage: 10,
    validUntil: '2024-10-30',
    category: 'Food & Dining',
    subCategory: 'Bakery',
    shopId: 's11',
    location: 'Theni Main',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1599317852936-7c09c91b8694?auto=format&fit=crop&q=80&w=800',
    originalPrice: 800,
    offerPrice: 720,
    code: "SWEET10"
  },
  {
    id: 'o14',
    title: 'Health Checkup Package',
    description: 'Full body checkup at just ₹999.',
    discountPercentage: 50,
    validUntil: '2024-12-31',
    category: 'Healthcare & Wellness',
    subCategory: 'Hospital',
    shopId: 's13',
    location: 'Periyakulam',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    originalPrice: 2000,
    offerPrice: 999,
    code: "HEALTH999"
  },
  {
    id: 'o15',
    title: 'Mens Shirt Combo',
    description: 'Buy 3 branded shirts for ₹1499.',
    discountPercentage: 30,
    validUntil: '2024-11-20',
    category: 'Fashion & Apparel',
    subCategory: 'Men',
    shopId: 's14',
    location: 'Theni Main',
    isSponsored: true,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800',
    originalPrice: 2100,
    offerPrice: 1499,
    code: "SHIRT3"
  },
  {
    id: 'o16',
    title: 'Power Bank Sale',
    description: '20000mAh Power Bank at 40% discount.',
    discountPercentage: 40,
    validUntil: '2024-10-15',
    category: 'Electronics & Appliances',
    subCategory: 'Accessories',
    shopId: 's12',
    location: 'Theni Main',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1609592424367-17e997a6f23f?auto=format&fit=crop&q=80&w=800',
    originalPrice: 1999,
    offerPrice: 1199,
    code: "POWER40"
  },
  {
    id: 'o17',
    title: 'Hari dental care',
    description: 'dental care ₹999.',
    discountPercentage: 50,
    validUntil: '2024-12-31',
    category: 'Healthcare & Wellness',
    subCategory: 'Hospital',
    shopId: 's13',
    location: 'Periyakulam',
    isSponsored: false,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    originalPrice: 1500,
    offerPrice: 999,
    code: "HEALTH999"
  },
  {
    id: 'o18',
    title: 'JCB',
    description: 'minimum 2 hours booking ₹999.',
    discountPercentage: 50,
    validUntil: '2024-12-31',
    category: 'Real Estate & Construction',
    subCategory: 'JCB',
    shopId: 's15',
    location: 'Periyakulam',
    isSponsored: false,
    image: 'https://wallpapercave.com/wp/wp2100850.jpg',
    originalPrice: 2000,
    offerPrice: 1500,
    code: "JCB10"
  },
  {
    id: 'o19',
    title: 'Crane',
    description: 'minimum 1 hours booking ₹1500. 9 Ton capacity to 50 Ton capacity',
    discountPercentage: 50,
    validUntil: '2024-12-31',
    category: 'Real Estate & Construction',
    subCategory: 'Crane',
    shopId: 's15',
    location: 'Periyakulam',
    isSponsored: false,
    image: 'https://tse4.mm.bing.net/th/id/OIP.zcGf2gsfKgqBHitoiTo_MAHaEG?rs=1&pid=ImgDetMain&o=7&rm=3',
    originalPrice: 2000,
    offerPrice: 999,
    code: "CRANE10"
  }
];

export const mockJobs: Job[] = [
  {
    id: 'j1',
    title: 'Sales Executive',
    companyName: 'Theni Mobiles & Gadgets',
    shopId: 's1',
    type: 'Full-time',
    salaryRange: '₹12,000 - ₹18,000',
    location: 'Theni Main',
    category: 'Electronics & Appliances',
    subCategory: 'Mobiles',
    isFeatured: true,
    postedDate: '2024-05-15',
    description: 'Looking for an experienced sales executive with good communication skills in Tamil and English.'
  },
  {
    id: 'j2',
    title: 'Fashion Designer',
    companyName: 'Saravana Textiles',
    shopId: 's2',
    type: 'Full-time',
    salaryRange: '₹15,000 - ₹25,000',
    location: 'Allinagaram',
    category: 'Fashion & Apparel',
    subCategory: 'Women',
    isFeatured: true,
    postedDate: '2024-05-10',
    description: 'Creative fashion designer needed for designing saree blouses and churidars.'
  },
  {
    id: 'j3',
    title: 'Delivery Partner',
    companyName: 'Green Leaf Groceries',
    shopId: 's4',
    type: 'Part-time',
    salaryRange: '₹8,000 - ₹12,000',
    location: 'Bodinayakanur',
    category: 'Grocery & Daily Needs',
    subCategory: 'Supermarket',
    isFeatured: false,
    postedDate: '2024-05-18',
    description: 'Two-wheeler required. Flexible timings for delivery partners.'
  },
  {
    id: 'j4',
    title: 'Chef / Cook',
    companyName: 'Spice Valley Restaurant',
    shopId: 's3',
    type: 'Full-time',
    salaryRange: '₹18,000 - ₹30,000',
    location: 'Periyakulam',
    category: 'Food & Dining',
    subCategory: 'Restaurant',
    isFeatured: false,
    postedDate: '2024-05-12',
    description: 'Experienced chef needed for South Indian and Chinese cuisine.'
  },
  {
    id: 'j5',
    title: 'Mechanic',
    companyName: 'Auto Care Experts',
    shopId: 's5',
    type: 'Full-time',
    salaryRange: '₹15,000 - ₹20,000',
    location: 'Theni Main',
    category: 'Automobile (Sales & Services)',
    subCategory: 'Car Service',
    isFeatured: false,
    postedDate: '2024-05-14',
    description: 'Car mechanic with minimum 2 years experience in multi-brand car service.'
  },
  {
    id: 'j6',
    title: 'Accountant',
    companyName: 'Theni Gold House',
    shopId: 's7',
    type: 'Full-time',
    salaryRange: '₹15,000 - ₹22,000',
    location: 'Theni Main',
    category: 'Jewellery & Accessories',
    subCategory: 'Gold',
    isFeatured: true,
    postedDate: '2024-05-16',
    description: 'B.Com graduate with Tally knowledge required for managing daily accounts.'
  }
];

export const mockAds: Ad[] = [
  {
    id: 'ad1',
    title: 'Mega Property Sale',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'home_banner',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad2',
    title: 'New Jewellery Showroom',
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'home_banner',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad3',
    title: 'Learn Digital Marketing',
    imageUrl: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'list_insert',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad4',
    title: 'Best Wedding Hall',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=600',
    redirectUrl: '#',
    placement: 'sidebar',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad5',
    title: 'School Admissions Open',
    imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'category_banner',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad6',
    title: 'Multi-Speciality Hospital',
    imageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'list_insert',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad7',
    title: 'Furniture Sale - Up to 40% Off',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'detail_page',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad8',
    title: 'Dream Home Loans',
    imageUrl: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?auto=format&fit=crop&q=80&w=1200',
    redirectUrl: '#',
    placement: 'list_insert',
    isActive: true,
    type: 'image'
  },
  {
    id: 'ad9',
    title: 'Experience Virtual Shopping',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1200',
    videoUrl: 'https://videos.pexels.com/video-files/3196238/3196238-hd_1920_1080_25fps.mp4',
    redirectUrl: '#',
    placement: 'home_banner',
    isActive: true,
    type: 'video'
  }
];